# Generated by Django 3.2.12 on 2023-05-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('mal', 'Malayalam'), ('ara', 'Arabic')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
